# Generated by Django 5.1.4 on 2025-02-18 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_alter_listing_starting_bid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='image_URL',
            field=models.URLField(blank=True, null=True),
        ),
    ]
