# Generated by Django 5.1.4 on 2025-02-19 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_alter_listing_highest_bid_alter_listing_winner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('msc', 'Misc'), ('ctb', 'Collectibles'), ('fnt', 'Furniture'), ('fsh', 'Fashion'), ('mrb', 'Memorabilia'), ('spt', 'Sports'), ('toy', 'Toys')], default='msc', max_length=3),
        ),
    ]
