name: Testing
on:
  push:
    paths:
      - 'week7/lecture/airline/**'

jobs:
  test_project:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Run Django unit tests
      run: |
        cd week7/lecture/airline
        pip3 install --user django
        python3 manage.py test